efs/efs/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='portfolio/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="portfolio/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='portfolio/password_reset_complete.html'), name='password_reset_complete'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

efs/portfolio/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import ChartData

app_name = 'portfolio'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('stock_list', views.stock_list, name='stock_list'),
    path('stock/create/', views.stock_new, name='stock_new'),
    path('stock/<int:pk>/edit/', views.stock_edit, name='stock_edit'),
    path('stock/<int:pk>/delete/', views.stock_delete, name='stock_delete'),

    path('investment_list', views.investment_list, name='investment_list'),
    path('investment/create/', views.investment_new, name='investment_new'),
    path('investment/<int:pk>/edit/', views.investment_edit, name='investment_edit'),
    path('investment/<int:pk>/delete/', views.investment_delete, name='investment_delete'),
    path('customer/<int:pk>/portfolio/', views.portfolio, name='portfolio'),
    url(r'^customers_json/', views.CustomerList.as_view()),
    path('customer/<int:cust_pk>/piechart/', views.pie_chart, name='pie-chart'),
    path('customer/<int:pk>/bar-chart/',ChartData.as_view(), name = 'chartdata'),
    path("password_reset", views.password_reset_request, name="password_reset"),




]

urlpatterns = format_suffix_patterns(urlpatterns)

efs/portfolio/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import requests


# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    cust_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=200)
    cell_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_number)


class Investment(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='investments')
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    acquired_value = models.DecimalField(max_digits=10, decimal_places=2)
    acquired_date = models.DateField(default=timezone.now)
    recent_value = models.DecimalField(max_digits=10, decimal_places=2)
    recent_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.acquired_date = timezone.now()
        self.save()

    def updated(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def results_by_investment(self):
        return self.recent_value - self.acquired_value

class Stock(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='stocks')
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    shares = models.DecimalField (max_digits=10, decimal_places=1)
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def initial_stock_value(self):
        return self.shares * self.purchase_price
    def current_stock_price(self):
        symbol_f = str(self.symbol)
        main_api = 'http://api.marketstack.com/v1/eod?'
        api_key = 'access_key=03ff666b843dc19b0ceb9147488cbc7d&limit=1&symbols='
        url = main_api + api_key + symbol_f
        json_data = requests.get(url).json()
        open_price = float(json_data["data"][0]["open"])
        share_value = open_price
        return share_value

    def current_stock_value(self):
        return float(self.current_stock_price()) * float(self.shares)

efs/portfolio/forms.py
from django import forms
from .models import Customer, Stock, Investment


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)

class StockForm(forms.ModelForm):
   class Meta:
       model = Stock
       fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date',)

class InvestmentForm(forms.ModelForm):
    class Meta:
        model = Investment
        fields = ('customer', 'category', 'description', 'acquired_value', 'acquired_date', 'recent_value','recent_date',)

efs/portfolio/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.db.models import Sum
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomerSerializer
import decimal

from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
import decimal


from django.db.models import Sum
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomerSerializer

import decimal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import get_template
from django.views import generic
from django.db.models import Sum

try:
    import simplejson as json
except ImportError:
    import json
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomerSerializer
from .models import *
from .forms import *
from django.views.generic import View

from django.contrib.auth.decorators import login_required, user_passes_test
import json


from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib import messages #import messages

now = timezone.now()
def home(request):
    return render(request, 'portfolio/home.html')

@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/customer_list.html',
                 {'customers': customer})

@login_required
def customer_edit(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   if request.method == "POST":
       # update
       form = CustomerForm(request.POST, instance=customer)
       if form.is_valid():
           customer = form.save(commit=False)
           customer.updated_date = timezone.now()
           customer.save()
           customer = Customer.objects.filter(created_date__lte=timezone.now())
           return render(request, 'portfolio/customer_list.html',
                         {'customers': customer})
   else:
        # edit
       form = CustomerForm(instance=customer)
   return render(request, 'portfolio/customer_edit.html', {'form': form})

@login_required
def customer_delete(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   customer.delete()
   return redirect('portfolio:customer_list')

@login_required
def stock_list(request):
   stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
   return render(request, 'portfolio/stock_list.html', {'stocks': stocks})

@login_required
def stock_new(request):
   if request.method == "POST":
       form = StockForm(request.POST)
       if form.is_valid():
           stock = form.save(commit=False)
           stock.created_date = timezone.now()
           stock.save()
           stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
           return render(request, 'portfolio/stock_list.html',
                         {'stocks': stocks})
   else:
       form = StockForm()
       # print("Else")
   return render(request, 'portfolio/stock_new.html', {'form': form})


@login_required
def stock_edit(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   if request.method == "POST":
       form = StockForm(request.POST, instance=stock)
       if form.is_valid():
           stock = form.save()
           # stock.customer = stock.id
           stock.updated_date = timezone.now()
           stock.save()
           stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
           return render(request, 'portfolio/stock_list.html', {'stocks': stocks})
   else:
       # print("else")
       form = StockForm(instance=stock)
   return render(request, 'portfolio/stock_edit.html', {'form': form})

@login_required
def stock_delete(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   stock.delete()
   return redirect('portfolio:stock_list')


@login_required
def investment_list(request):
    investments = Investment.objects.filter(recent_date__lte=timezone.now())
    return render(request, 'portfolio/investment_list.html', {'investments': investments})

login_required
def investment_new(request):
    if request.method == "POST":
        form = InvestmentForm(request.POST)
        if form.is_valid():
            investment = form.save(commit=False)
            investment.created_date = timezone.now()
            investment.save()
            investments = Investment.objects.filter(recent_date__lte=timezone.now())
            return render(request, 'portfolio/investment_list.html',
                          {'investments': investments})
    else:
        form = InvestmentForm()
        # print("Else")
    return render(request, 'portfolio/investment_new.html', {'form': form})

@login_required
def investment_edit(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    if request.method == "POST":
        form = InvestmentForm(request.POST, instance=investment)
        if form.is_valid():
            investment = form.save()
            # investment.customer = investment.id
            investment.updated_date = timezone.now()
            investment.save()
            investments = Investment.objects.filter(recent_date__lte=timezone.now())
            return render(request, 'portfolio/investment_list.html', {'investments': investments})
    else:
        # print("else")
        form = InvestmentForm(instance=investment)
    return render(request, 'portfolio/investment_edit.html', {'form': form})

@login_required
def investment_delete(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    investment.delete()
    return redirect('portfolio:investment_list')


@login_required
def portfolio(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    investments = Investment.objects.filter(customer=pk)
    stocks = Stock.objects.filter(customer=pk)
    sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
    sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
    # overall_investment_results = sum_recent_value-sum_acquired_value
    # Initialize the value of the stocks
    sum_current_stocks_value = 0
    sum_of_initial_stock_value = 0
    sum_current_investment_value = 0
    sum_of_initial_investment_value = 0

    # Loop through each stock and add the value to the total
    for stock in stocks:
        sum_current_stocks_value += stock.current_stock_value()
        sum_of_initial_stock_value += stock.initial_stock_value()

    result = decimal.Decimal(sum_current_stocks_value) - (sum_of_initial_stock_value)

    for investment in investments:
        sum_current_investment_value += investment.recent_value
        sum_of_initial_investment_value += investment.acquired_value

    result1 = sum_current_investment_value - sum_of_initial_investment_value

    Total_current_investments = float(sum_current_stocks_value) + float(sum_current_investment_value)
    Total_initial_investments = float(sum_of_initial_investment_value) + float(sum_of_initial_stock_value)
    Grand_total = result + result1

    return render(request, 'portfolio/portfolio.html', {'customer': customer,
                                                        'customers': customers,
                                                        'investments': investments,
                                                        'stocks': stocks,
                                                        'sum_acquired_value': sum_acquired_value,
                                                        'sum_recent_value': sum_recent_value,
                                                        'result': result,
                                                        'sum_current_stocks_value': sum_current_stocks_value,
                                                        'sum_of_initial_stock_value': sum_of_initial_stock_value,
                                                        'sum_current_investment_value': sum_current_investment_value,
                                                        'sum_of_initial_investment_value': sum_of_initial_investment_value,
                                                        'result1': result1,
                                                        'Total_current_investments': Total_current_investments,
                                                        'Total_initial_investmensts': Total_initial_investments,
                                                        'Grand_total': Grand_total})




# List at the end of the views.py
# Lists all customers
class CustomerList(APIView):

    def get(self,request):
        customers_json = Customer.objects.all()
        serializer = CustomerSerializer(customers_json, many=True)
        return Response(serializer.data)


@login_required
def pie_chart(request, cust_pk):
    labels = []
    data = []

    customer = get_object_or_404(Customer, pk=cust_pk)

efs/portfolio/templates/portfolio/customer_delete.html
 {% block body_block %}
 {% extends 'portfolio/base.html' %}
    <h1>Delete {{ customer.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'portfolio:home' pk=customer.cust_number %} ">Cancel</a>
    </form>
{% endblock %}

efs/portfolio/templates/portfolio/customer_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Edit Customer</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

efs/portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
            {% if user.is_authenticated %}
                <div class="page-container">

                    <h2 class="top-menu">Hello {{ user.username }},</h2>
                    <p>Please choose from below options.</p>

                </div>
            {% endif %}
            <div class="content container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="links">
                            <!-- Example row of columns -->
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                                        <div class="caption">
                                            <h2>Customer</h2>
                                            <p>We see our success in our customers success, it gives us an immense
                                                pleasure when our
                                                advises
                                                turn out to be fruitful. </p>
                                            <p><a class="btn btn-primary" href="{% url 'portfolio:customer_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/nonstock.jpg" %}" alt="non-stock"/>
                                        <div class="caption">
                                            <h2>Non-Stock Investments</h2>
                                            <p>Our team also provides advice for Non-Stock investments.</p>
                                            <p><a class="btn btn-primary" href="{% url 'portfolio:investment_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/stocks.jpg" %}" alt="stocks"/>
                                        <div class="caption">
                                            <h2>Stocks</h2>
                                            <p>Our Stock portfolios vary across industries.</p>
                                            <p><a class="btn btn-primary" href="{% url 'portfolio:stock_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </body>
    </html>
{% endblock %}

efs/portfolio/templates/portfolio/investment_delete.html
{% block body_block %}
{% extends 'portfolio/base.html' %}

<h1>Delete {{ investment.name }}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'portfolio:home' pk=stock.cust_number %} ">Cancel</a>
</form>
{% endblock %}

efs/portfolio/templates/portfolio/investment_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Edit Investment</h1>
<form method="POST" class="stock-form">{% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="save btn btn-default">Update</button>
</form>
{% endblock %}

efs/portfolio/templates/portfolio/investment_new.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Add a New Investment</h1>
<form method="POST" class="investment-form">{% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

efs/portfolio/templates/portfolio/password_reset.html
{% extends "portfolio/base.html" %}
{% block content %}

{% load crispy_forms_tags %}

<!--Reset Password-->
<div class="container p-5">
  <h2 class="font-weight-bold mt-3">Reset Password</h2>
  <hr>
  <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
  <form method="POST">
    {% csrf_token %}
    {{ password_reset_form|crispy }}
    <button class="btn btn-primary" type="submit">Send email</button>
  </form>
</div>

{% endblock %}

efs/portfolio/templates/portfolio/password_reset_complete.html
{% extends "portfolio/base.html" %}
{% block content %}

<!--Password Reset Complete-->
<div class="container p-4">
  <h2 class="font-weight-bold mt-3">Password reset complete</h2>
  <hr>
  <p>Your password has been set. You may go ahead and log in now.</p>
  <a href="/login" class="btn btn-primary">Log in</a>
</div>

{% endblock %}

efs/portfolio/templates/portfolio/password_reset_confirm.html
{% extends "portfolio/base.html" %}
{% block content %}

{% load crispy_forms_tags %}

<!--Password Reset Confirm-->
<div class="container p-5">
  <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
  <hr>
  <p>Please enter your new password.</p>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Reset password</button>
  </form>
</div>

{% endblock %}

efs/portfolio/templates/portfolio/password_reset_done.html
{% extends "portfolio/base.html" %}


{% block content %}

<!--Password reset sent-->
<div class="container p-5">
  <h2 class="font-weight-bold mt-3">Password reset sent</h2>
  <hr>
  <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
</div>

{% endblock %}

efs/portfolio/templates/portfolio/pie_chart.html
{% extends 'portfolio/base.html' %}
{% block content %}
<div class="page-header">
  <h4>Graphical representation for the {{customer.name}}'s portfolio</h4>
</div>
<div id="container" style="width: 60%;">
  <canvas id="pie-chart"></canvas>
  <br>
  <canvas id="population-chart" data-url="{% url 'portfolio:chartdata' customer.pk %}"></canvas>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>
  var defaultData = []
  var labels1 = [];
  var config = {
            type: 'pie',
            data: {
              datasets: [{
                data: {{ data|safe }},
          backgroundColor: [
            '#008000', '#008080', '#0000FF', '##000000', '#D3D3D3','#FF7F50','#D2691E'
          ],
          label: 'Investments'
  }],
  labels: {{ labels|safe }}
  },
  options: {
    responsive: true
  }
  };


  window.onload = function() {
    var ctx = document.getElementById('pie-chart').getContext('2d');
    window.myPie = new Chart(ctx,config);
  };

  $(function () {

    var $populationChart = $("#population-chart");
    $.ajax({
      url: $populationChart.data("url"),
      success: function (data) {

        var ctx = $populationChart[0].getContext("2d");

        new Chart(ctx, {
          type: 'bar',
          data: {
            labels: data.labels1,
            datasets: [{
              label: 'Portfolio',
              backgroundColor: '#FF7F50',
              data: data.data1
            }]
          },
          options: {
            responsive: true,
            legend: {
              position: 'top',
            },
            title: {
              display: true,
              text: 'Portfolio Bar Chart'
            }
          }
        });

      }
    });

  });




</script>
{% endblock content %}

efs/portfolio/templates/portfolio/portfolio.html
{% extends 'portfolio/base.html' %}
{% load humanize %}
{% block content %}
{% load mathfilters %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Eagle Financial</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>

<body>
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    Eagle Financial Services, your Midwest Financial Services Partner.
                </div>
            </div>
        </div>
    </div>
    <a href="{% url 'portfolio:pie-chart' customer.pk %}" class="btn btn-info" role="button" style="float: left;">Graphical View</a>


</div>
<div class="row">
    <h1 style="padding-left: 15Px">Customer Portfolio</h1>
</div>

<div class="row">
    <h2 style="padding-left: 15Px">Overall Portfolio Performance</h2>
</div>
<div class="row">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Portfolio Initial Investment</th>
            <th>Portfolio Current Investment</th>
            <th>Grand Total Results </th>

        </tr>
        </thead>
        <tbody>
        <tbody>
        <tr>
            <td>{{ Total_initial_investmensts|intcomma }}</td>
            <td>{{ Total_current_investments|intcomma }}</td>
            <td>{{ Grand_total|floatformat|intcomma }}</td>
        </tr>
        </tbody>

        </tbody>
    </table>
<div class="row">
    <h3 style="padding-left: 15Px">Stocks Information</h3>
</div>
<div class="row">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer</th>
            <th>Symbol</th>
            <th>Name</th>
            <th>Shares</th>
            <th>Initial Stock Price</th>
            <th>Initial Stock Value</th>
            <th>Current Stock Price</th>
            <th>Current Stock Value</th>
            <th scope ="col">Result</th>

        </tr>
        </thead>
        <tbody>
        {% for stock in stocks %}
        <tr>
            <td>{{ stock.customer }}</td>
            <td>{{ stock.symbol }}</td>
            <td>{{ stock.name }}</td>
            <td>{{ stock.shares|intcomma }}</td>
            <td>{{ stock.purchase_price|intcomma }}</td>
            <td>{{ stock.initial_stock_value|intcomma }}</td>
            <td>{{ stock.current_stock_price|intcomma }}</td>
            <td>{{ stock.current_stock_value|floatformat|intcomma }}</td>
            <td>{{ result|floatformat|intcomma }}</td>

        </tr>

        {% endfor %}
        </tbody>
    </table>
</div>


    <div class="row">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr class="bg-info">
                        <th>#</th>
                        <th>Total of Initial stocks</th>
                        <th>Total of Current stocks</th>
                        <th>Results</th>
                    </tr>
                    </thead>
                    <tbody>
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{ sum_of_initial_stock_value|intcomma }}</td>
                <td>{{ sum_current_stocks_value|floatformat|intcomma }}</td>
                <td>{{ result|floatformat|intcomma }}</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="row">
        <h4 style="padding-left: 15Px">Investment  Information</h4>
    </div>
    <div  class="table-responsive text-nowrap">
        <table class="table table-striped">
            <thead class="thead-light">
            <tr class="bg-info">
                <th>#</th>
                <th>Customer</th>
                <th>Category</th>
                <th>Description</th>
                <th>Acquired Value</th>
                <th>Acquired Date</th>
                <th>Recent Value</th>
                <th>Recent Date</th>
                <th scope ="col">Result</th>

            </tr>
            </thead>
            <tbody>
            {% for investment in investments %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{ investment.customer }}</td>
                <td>{{ investment.category }}</td>
                <td>{{ investment.description }}</td>
                <td>{{ investment.acquired_value|intcomma }}</td>
                <td>{{ investment.acquired_date }}</td>
                <td>{{ investment.recent_value|intcomma }}</td>
                <td>{{ investment.recent_date }}</td>
                <td>{{ investment.results_by_investment|intcomma}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

    <div  class="table-responsive text-nowrap">
        <table class="table table-striped">
            <thead class="thead-light">
            <tr class="bg-info">
                <th>#</th>
                <th>Total Initial Investments</th>
                <th>Total Current Investments</th>
                <th scope ="col">Result</th>

            </tr>
            </thead>
            <tbody>


            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{ sum_of_initial_investment_value|intcomma }}</td>
                <td>{{ sum_current_investment_value|intcomma }}</td>
                <td>{{ result1|intcomma }}</td>
            </tr>
            </tbody>
        </table>
    </div>

    {% endblock %}

efs/portfolio/templates/portfolio/stock_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Stock</h1>
    <form method="POST" class="stock-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

efs/portfolio/templates/portfolio/stock_new.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New Stock</h1>
    <form method="POST" class="stock-form">{% csrf_token %}
          {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}